services:
  db:
    image: mysql
    container_name: godockerDB
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: godocker
    healthcheck:
      test: ["CMD", "mysql", "-u", "docker", "-ppassword", "-e", "show databases"]
      interval: 30s
    ports:
    - "3307:3306"

  db_test:
    image: mysql
    container_name: godockerDB_test
    environment:
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: godocker_test
    healthcheck:
      test: ["CMD", "mysql", "-u", "docker", "-ppassword", "-e", "show databases"]
      interval: 30s
    ports:
    - "3308:3306"
    depends_on:
      db:
        condition: service_healthy

  app:
    container_name: go-app
    build: .
    restart: always
    ports:
     - 8000:8000
    depends_on:
      db_test:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8081:8080
    depends_on:
      db_test:
        condition: service_healthy