port: 8000
database:
  driver: "mysql"
  address: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root1234"
  name: "suit"
database_test:
  driver: "mysql"
  address: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root1234"
  name: "suit_test"